---
#Created on 11 14, 2024
#@author: <Cui>
#@bref: 网络的各种配置


# 数据参数
data:
  height: 224
  width: 224
  input_size: 50176
  download: false
  num_classes: 23

# 网络参数
net:
#  hidden_layer_size: 128
#  output_size: 10
#  activation_function: ReLU

# 优化器参数
optimizer:
  type: Adam
  lr: 0.001
#  weight_decay: 0.0001

# 训练参数
train:
  batch_size: 20
  num_workers: 2
  num_epochs: 500

  drop_last: true
  use_save_model: true  # 使用之前训练的模型继续训练，如果是新的模型，则设置为 false，旧的模型，则设置为 true

  not_freeze_conv: true # 使用预训练模型后，是否冻结卷积层
  not_freeze_fn: true # 使用预训练模型后，是否冻结全连接层

  save_model: true
  save_model_freq: 1
  save_check_point: true
  save_check_point_freq: 1

val:
  preference_accuracy: 0.9 #模型想要训练的精度，达到此进度，模型训练将会结束
  batch_size: 20
  num_workers: 2
  use_save_model: true
  drop_last: true